import { writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { generateLevel } from './level';
import { LEVEL_PRINTS } from './levelprints';
import { levelPrint } from './levelprint';
import { THEMES } from './textures';

/**
 * The ordinary floors do not move. `generateLevel` with no recipe must build
 * exactly the floor it built before missions existed: these prints were
 * recorded from the generator as it was, 50 seeds on each of floors 0-5.
 * Re-record (WG_RECORD_LEVELS=1) only for a change meant to move every floor.
 */
const SEEDS = Array.from({ length: 50 }, (_, i) => (i + 1) * 104723);
const FLOORS = [0, 1, 2, 3, 4, 5];

function prints(f: number): Record<string, number> {
  const out: Record<string, number> = {};
  const theme = THEMES[f % THEMES.length];
  if (theme === undefined) throw new Error('theme');
  for (const seed of SEEDS) out[`${f}:${seed}`] = levelPrint(generateLevel(f, theme, seed, true));
  return out;
}

describe('Ordinary floors', () => {
  if (process.env.WG_RECORD_LEVELS === '1') {
    it('records the prints', { timeout: 120_000 }, () => {
      const all = Object.assign({}, ...FLOORS.map((f) => prints(f))) as Record<string, number>;
      const body = Object.entries(all).map(([k, v]) => `  '${k}': ${v},`).join('\n');
      writeFileSync(new URL('./levelprints.ts', import.meta.url), `/** GENERATED by levelprint.test.ts (WG_RECORD_LEVELS=1): the ordinary floors before missions. */\nexport const LEVEL_PRINTS: Readonly<Record<string, number>> = {\n${body}\n};\n`);
    });
    return;
  }

  it('has a print for every seed on every floor', () => {
    expect(Object.keys(LEVEL_PRINTS)).toHaveLength(SEEDS.length * FLOORS.length);
  });

  it.each(FLOORS)('floor %i: the same floor for every recorded seed', { timeout: 30_000 }, (f) => {
    const now = prints(f);
    const moved = Object.keys(now).filter((k) => LEVEL_PRINTS[k] !== now[k]);
    expect(moved, `floors that changed: ${moved.slice(0, 8).join(', ')}`).toEqual([]);
  });

});
