// Extracts the office sim's real ticket + KB content into a small JSON the
// dungeon crawler (crawler.html) reads, so the crawler never has to load the
// whole world graph or the wasm core. Run: node scripts/crawler-content.mjs
import { writeFileSync } from 'node:fs';
import { createServer } from 'vite';

const server = await createServer({
  logLevel: 'error',
  server: { middlewareMode: true, hmr: false },
  appType: 'custom',
  define: { __APP_VERSION__: '"x"', __CORE_VERSION__: '"x"' },
});

try {
  const tickets = await server.ssrLoadModule('/src/world/tickets/index.ts');
  const kb = await server.ssrLoadModule('/src/world/kb/index.ts');
  const setups = [
    (await server.ssrLoadModule('/src/world/company.ts')).companySetup(),
    (await server.ssrLoadModule('/src/world/msp-company.ts')).mspSetup(),
    (await server.ssrLoadModule('/src/world/second-company.ts')).bodgeSetup(),
    (await server.ssrLoadModule('/src/world/corporate-company.ts')).halcyonSetup(),
  ];
  const names = new Map();
  for (const ops of setups) {
    for (const op of ops) {
      if (op.op === 'addNode' && op.node.kind === 'person') {
        names.set(op.node.id, { name: op.node.fields.name, title: op.node.fields.title ?? '' });
      }
    }
  }

  const seen = new Set();
  const out = [];
  for (const t of tickets.WORLD_TICKETS) {
    const d = t.def;
    if (seen.has(d.flavor.title) || !t.paths?.length) continue;
    seen.add(d.flavor.title);
    const who = names.get(d.reporter);
    const article = kb.findKbArticle(d.kb_ref);
    out.push({
      id: d.id,
      title: d.flavor.title,
      body: d.flavor.body,
      reporter: who?.name ?? 'A user',
      reporterTitle: typeof who?.title === 'string' ? who.title : '',
      archetype: d.archetype,
      cause: t.cause ?? '',
      fixes: t.paths.map((p) => p.label),
      urgency: t.true_urgency ?? 1,
      claimed: t.claimed_urgency ?? 1,
      kb: article ? { title: article.title, resolution: article.resolution.slice(0, 4) } : null,
    });
  }
  const header = '// GENERATED by scripts/crawler-content.mjs from src/world/tickets + src/world/kb.\n'
    + '// Do not edit by hand; re-run the script after changing ticket content.\n'
    + "import type { CrawlerTicket } from './ticket-type';\n\n"
    + 'export const TICKETS: readonly CrawlerTicket[] = [\n';
  const body = out.map((t) => '  ' + JSON.stringify(t) + ',\n').join('');
  writeFileSync(
    new URL('../src/crawler/content/tickets.ts', import.meta.url),
    header + body + '];\n',
  );
  console.log(`wrote ${out.length} tickets`);
} finally {
  await server.close();
}
